#!/bin/sh
### BEGIN INIT INFO
# Provides: STARTUP_DEVELOPMENT
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir="Project+_path"
user="user"
cmd="command"

name=`basename $0` # basename means filename
pid_dir="/var/run/nqa"
log_dir="/var/log/nqa"
pid_file="/var/run/nqa/$name.pid"
stdout_log="/var/run/nqa/$name.log"
stderr_log="/var/run/nqa/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

create_log() {
  sudo mkdir "pid_dir"
  sudo mkdir "log_dir"
  sudo chown '$user' "log_dir"
  sudo chown '$user' "pid_dir"
}

delete_log() {
sudo rm -rf "pid_dir"
sudo rm -rf "log_dir"
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
	'create_log'
        echo "Starting $name"
        cd "$dir"
	$cmd >> "$stdout_log" 2>> "$stderr_log" &
#        sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        sudo echo $! > "$pid_file"
        if ! is_running; then
            #echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
	   'delete_log'
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
